/* AUTO-GENERATED by sync-kb.js — do not edit.
 * Source of truth: payroll-compliance-chatbot.html
 * Re-generate with: npm run sync
 */

var SRC = {
  epf: {a:'KWSP (EPF)', t:'Mandatory Contribution - payments subject to EPF',
        p:'Employer > Responsibilities > Mandatory Contribution',
        l:'EPF Act 1991, s.2 (definition of "wages") & Third Schedule', u:'https://www.kwsp.gov.my'},
  socso:{a:'PERKESO (SOCSO)', t:'Contribution - wages subject to SOCSO & EIS',
        p:'Our Services > Employer & Employee > Contribution',
        l:'Employees Social Security Act 1969, s.2; Employment Insurance System Act 2017, s.2', u:'https://www.perkeso.gov.my'},
  lhdn: {a:'LHDN', t:'Employment income, perquisites & Monthly Tax Deduction (PCB)',
        p:'Individual > Employment Income / Public Rulings > Perquisites & Benefits',
        l:'Income Tax Act 1967, s.13(1) & Schedule 6 exemptions', u:'https://www.hasil.gov.my'},
  hrdf: {a:'HRD Corp', t:'Levy - wages used for levy computation',
        p:'Employer > Levy > Levy Calculation',
        l:'PSMB Act 2001, s.2 (definition of "wages") & s.14', u:'https://hrdcorp.gov.my'},
  skbbk:{a:'PERKESO (SOCSO)', t:'Skim Kemalangan Bukan Bencana Kerja (SKBBK) / LINDUNG 24 JAM — scheme page and official FAQ',
        p:'perkeso.gov.my > Skim Kemalangan Bukan Bencana Kerja (LINDUNG 24 JAM); FAQ Ver2.1/FAQL24/JUN26',
        l:'Akta Keselamatan Sosial Pekerja 1969 (Akta 4), s.2(24); Jadual Ketiga (Kadar Caruman), Akta Keselamatan Sosial Pekerja (Pindaan) 2026 [Akta A1788]',
        u:'https://www.perkeso.gov.my/skim-kemalangan-bukan-bencana-kerja-lindung-24-jam.html'},
  act265:{a:'Laws of Malaysia (AGC)', t:'Employment Act 1955 (Act 265) — official reprint, as at 1 January 2023',
        p:'lom.agc.gov.my > Principal Acts > Act 265',
        l:'Employment Act 1955 (Act 265)', u:'https://lom.agc.gov.my'},
  kwspEmp:{a:'KWSP (EPF)', t:'Employer Mandatory Contribution — who must be contributed for',
        p:'Employer > Responsibilities > Mandatory Contribution',
        l:'EPF Act 1991, s.43(1) and Third Schedule', u:'https://www.kwsp.gov.my/en/employer/responsibilities/mandatory-contribution'},
  perkesoCov:{a:'PERKESO (SOCSO)', t:'Pekerja Bermajikan — who must be registered and contributed for',
        p:'Perkhidmatan Kami > Perlindungan > Pekerja Bermajikan',
        l:'Akta Keselamatan Sosial Pekerja 1969 (Akta 4); Akta Sistem Insurans Pekerjaan 2017 (Akta 800)',
        u:'https://www.perkeso.gov.my/perkhidmatan-kami/perlindungan/pekerja-bermajikan.html'},
  ea:   {a:'JTKSM / MOHR', t:'Employment Act 1955 (Amendment 2022) and subsidiary regulations — Peninsular Malaysia',
        p:'Soalan Lazim > Akta Kerja 1955 (Pindaan 2022)',
        l:'Employment Act 1955, as amended 2022', u:'https://jtksm.mohr.gov.my'},
  mygov:{a:'MyGovernment national portal', t:'Labour Law — Employment Act 1955 (Amendment 2022), Sabah and Sarawak Labour Ordinances',
        p:'Topics > Labour Law',
        l:'Employment Act 1955 (Amendment 2022); Sabah Labour Ordinance (Amendment) 2024; Sarawak Labour (Amendment) Ordinance 2024',
        u:'https://www.malaysia.gov.my/en/topics/labour-law'},
  sabah:{a:'Jabatan Tenaga Kerja Sabah', t:'Sabah Labour Ordinance — FAQ',
        p:'Pusat Bantuan > Soalan Lazim (FAQ)',
        l:'Sabah Labour Ordinance (Amendment) 2024', u:'https://www.jtksabah.gov.my'},
  lhdnEmp:{a:'LHDN', t:'Tanggungjawab Majikan — employer responsibilities, forms and deadlines',
        p:'Majikan > Tanggungjawab Majikan',
        l:'Income Tax Act 1967 — employer obligations', u:'https://www.hasil.gov.my/majikan/tanggungjawab-majikan/'},
  swk:  {a:'Jabatan Tenaga Kerja Sarawak', t:'Sarawak Labour Ordinance (Amendment) 2024',
        p:'Perundangan > RUU SLO (Pindaan) 2024',
        l:'Sarawak Labour (Amendment) Ordinance 2024', u:'https://www.jtkswk.gov.my'}
};

var YES='Subject', NO='Not subject', CHK='Confirm';

/* ---------------------------------------------------------------
   Component knowledge base.
   v: verdict, r: one-line reason. src: which official sources back it.
----------------------------------------------------------------*/
var KB = [
{
  id:'travel-fixed', ms:'Elaun pengangkutan/perjalanan tetap bulanan', label:'Fixed transport / travelling / petrol allowance (paid monthly, not receipt-based)',
  keys:['transport allowance','travelling allowance','travel allowance','petrol allowance','elaun perjalanan','elaun pengangkutan','car allowance','mileage allowance','fixed transport'],
  epf:{v:NO, r:'Travelling allowance and the value of any travelling concession are expressly excluded from the EPF definition of wages.'},
  socso:{v:NO, r:'Travelling allowance is expressly excluded from wages under the Employees Social Security Act.'},
  lhdn:{v:YES, r:'A cash allowance is gross employment income under s.13(1)(a); travelling for official duties is exempt only up to the gazetted annual cap, and the excess is taxable.'},
  hrdf:{v:YES, r:'Levy is computed on basic salary plus fixed allowances, so a fixed monthly transport allowance forms part of levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['This is the classic four-way split: EPF-exempt, SOCSO-exempt, partly taxable, and levy-liable. Do not copy one domain’s treatment across to another.',
         'If the payment is a claim reimbursed against receipts or a mileage log instead of a fixed monthly sum, ask again about "petrol reimbursement" — the treatment differs.']
},
{
  id:'travel-reimb', ms:'Tuntutan petrol/tol/batu perjalanan berdasarkan resit', label:'Petrol / mileage / toll reimbursement claimed against receipts or a mileage log',
  keys:['petrol claim','mileage claim','toll claim','travel reimbursement','petrol reimbursement','reimburse','claim against receipt','tuntutan'],
  epf:{v:NO, r:'Reimbursement of expenses incurred in carrying out the employment is not remuneration, so it is not EPF wages.'},
  socso:{v:NO, r:'Sums paid to defray special expenses entailed by the nature of the employment are excluded from SOCSO wages.'},
  lhdn:{v:NO, r:'Not taxable to the extent it reimburses actual expenditure on official duties; any portion covering private travel is a taxable perquisite.'},
  hrdf:{v:NO, r:'A variable reimbursement is not a fixed allowance and is excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Keep the receipts or mileage log on file — without supporting documents, an auditor can treat the payment as a fixed allowance and reclassify it in all four domains.']
},
{
  id:'meal', ms:'Elaun makan', label:'Meal allowance',
  keys:['meal allowance','food allowance','elaun makan','elaun makanan','lunch allowance'],
  epf:{v:YES, r:'Meal allowance is not in the excluded list, so it forms part of EPF wages.'},
  socso:{v:YES, r:'Included as remuneration payable in money under the SOCSO definition of wages.'},
  lhdn:{v:CHK, r:'Commonly exempt where provided on a regular basis at the same rate to all employees; amounts beyond a reasonable rate are taxable. Confirm the current exemption conditions with LHDN.'},
  hrdf:{v:YES, r:'Subject where paid as a fixed monthly allowance; an ad-hoc overtime meal claim is not fixed wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['An overtime meal claim paid only on days OT is worked behaves like a reimbursement, not a fixed allowance — confirm which one your payroll item is.']
},
{
  id:'housing', ms:'Elaun perumahan (tunai)', label:'Housing allowance paid in cash',
  keys:['housing allowance','accommodation allowance','elaun rumah','elaun perumahan','rental allowance'],
  epf:{v:YES, r:'A cash housing allowance is remuneration and is not in the excluded list.'},
  socso:{v:YES, r:'Included as remuneration payable in money to the employee.'},
  lhdn:{v:YES, r:'Gross employment income under s.13(1)(a).'},
  hrdf:{v:YES, r:'A fixed monthly allowance forms part of levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Living accommodation actually provided by the employer is a different animal — it is a s.13(1)(c) benefit valued under LHDN rules, not a cash allowance.']
},
{
  id:'phone', ms:'Elaun telefon', label:'Mobile phone / telephone allowance',
  keys:['phone allowance','telephone allowance','handphone allowance','mobile allowance','elaun telefon','broadband allowance'],
  epf:{v:YES, r:'A fixed cash phone allowance is remuneration and is not in the excluded list.'},
  socso:{v:YES, r:'Included as remuneration payable in money.'},
  lhdn:{v:YES, r:'A cash allowance is taxable income; the exemption applies to a phone or line registered in and paid by the employer, not to cash paid to the employee.'},
  hrdf:{v:YES, r:'Subject where paid as a fixed monthly allowance.'},
  src:['epf','socso','lhdn','hrdf'],
  clarify:'Is this a fixed cash allowance paid to the employee, or a line/device registered in the company’s name and paid directly by the company? A company-registered line is a benefit, not wages, and none of the four apply.'
},
{
  id:'ot', ms:'Bayaran kerja lebih masa', label:'Overtime payment',
  keys:['overtime','ot payment','kerja lebih masa','lebih masa','ot pay'],
  epf:{v:NO, r:'Overtime payment is expressly excluded from the EPF definition of wages.'},
  socso:{v:YES, r:'Overtime is expressly included in SOCSO wages — the opposite of the EPF treatment.'},
  lhdn:{v:YES, r:'Gross employment income under s.13(1)(a) and subject to PCB.'},
  hrdf:{v:NO, r:'Levy is computed on basic salary plus fixed allowances; overtime is excluded.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['This is the pair payroll clerks get wrong most often: EPF says no, SOCSO says yes.',
         'Overtime rates and eligibility for employees within the First Schedule are set by the Employment Act 1955 (JTKSM).'],
  extra:['ea']
},
{
  id:'bonus', ms:'Bonus tahunan/kontraktual', label:'Annual / contractual bonus',
  keys:['bonus','annual bonus','contractual bonus','ex gratia','thr','incentive bonus','performance bonus'],
  epf:{v:YES, r:'Bonus is remuneration and is not in the EPF excluded list.'},
  socso:{v:NO, r:'Annual bonus is expressly excluded from SOCSO wages.'},
  lhdn:{v:YES, r:'Taxable; PCB is computed under the additional remuneration formula, not the normal monthly formula.'},
  hrdf:{v:NO, r:'Bonus is not part of basic salary or fixed allowances and is excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Because bonus PCB uses the additional-remuneration formula, running it through the normal monthly table will under-deduct.']
},
{
  id:'commission', ms:'Komisen', label:'Commission',
  keys:['commission','komisen','sales commission'],
  epf:{v:YES, r:'Commission is remuneration and is not in the EPF excluded list.'},
  socso:{v:YES, r:'Commission is included in SOCSO wages.'},
  lhdn:{v:YES, r:'Taxable employment income; PCB applies (additional remuneration formula where it is not paid at a fixed monthly amount).'},
  hrdf:{v:NO, r:'Variable commission is not basic salary or a fixed allowance and is excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'service-charge', ms:'Caj perkhidmatan', label:'Service charge distributed to employees',
  keys:['service charge','caj perkhidmatan','service point'],
  epf:{v:NO, r:'Service charge is expressly excluded from the EPF definition of wages.'},
  socso:{v:YES, r:'Service charge is included in SOCSO wages.'},
  lhdn:{v:YES, r:'Taxable employment income.'},
  hrdf:{v:NO, r:'Not basic salary or a fixed allowance; excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Distribution of service charge to employees is also governed by the Employment Act 1955 — check the JTKSM provisions if the question is about how much must be passed on.'],
  extra:['ea']
},
{
  id:'shift', ms:'Elaun syif', label:'Shift allowance',
  keys:['shift allowance','elaun syif','elaun shift','night shift allowance'],
  epf:{v:YES, r:'Remuneration for working a shift pattern; not in the excluded list.'},
  socso:{v:YES, r:'Included as remuneration payable in money.'},
  lhdn:{v:YES, r:'Gross employment income under s.13(1)(a).'},
  hrdf:{v:CHK, r:'Subject where paid as a fixed monthly amount; excluded where it varies with the shifts actually worked. Confirm which basis applies.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'attendance', ms:'Elaun kehadiran/insentif', label:'Attendance / good-behaviour / productivity incentive',
  keys:['attendance allowance','attendance incentive','good behaviour','productivity incentive','elaun kehadiran','incentive allowance'],
  epf:{v:YES, r:'Incentive payments are remuneration and are not in the EPF excluded list.'},
  socso:{v:YES, r:'Incentive and good-behaviour payments are included in SOCSO wages.'},
  lhdn:{v:YES, r:'Taxable employment income.'},
  hrdf:{v:CHK, r:'Subject only if paid as a fixed monthly amount; a variable performance-based incentive is excluded. Confirm which basis applies.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'cola', ms:'Elaun sara hidup (COLA)', label:'Cost of living allowance (COLA)',
  keys:['cost of living','cola','elaun sara hidup','living allowance'],
  epf:{v:YES, r:'COLA is remuneration and is not in the EPF excluded list.'},
  socso:{v:YES, r:'Included as remuneration payable in money.'},
  lhdn:{v:YES, r:'Gross employment income under s.13(1)(a).'},
  hrdf:{v:YES, r:'A fixed monthly allowance forms part of levy wages.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'retrench', ms:'Faedah pemberhentian/pembuangan kerja', label:'Retrenchment / termination / lay-off benefit',
  keys:['retrenchment','termination benefit','lay off','layoff','vss','mss','severance','pampasan','termination payment'],
  epf:{v:NO, r:'Retrenchment, lay-off and termination benefits are expressly excluded from EPF wages.'},
  socso:{v:NO, r:'Payments on dismissal, retrenchment or retirement are excluded from SOCSO wages.'},
  lhdn:{v:CHK, r:'Compensation for loss of employment is taxable in principle, but a Schedule 6 exemption applies per completed year of service. Confirm the current exempt amount and conditions with LHDN before computing PCB.'},
  hrdf:{v:NO, r:'Not basic salary or a fixed allowance; excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Minimum entitlement is set by the Employment (Termination and Lay-Off Benefits) Regulations 1980 under the Employment Act 1955 — check JTKSM for the entitlement, LHDN for the tax treatment.'],
  extra:['ea']
},
{
  id:'gratuity', ms:'Ganjaran/faedah persaraan', label:'Gratuity / retirement benefit',
  keys:['gratuity','retirement benefit','ganjaran','retirement gratuity','pension payment'],
  epf:{v:NO, r:'Gratuity and retirement benefits are expressly excluded from EPF wages.'},
  socso:{v:NO, r:'Gratuity payable on discharge or retirement is excluded from SOCSO wages.'},
  lhdn:{v:CHK, r:'Taxable unless a Schedule 6 exemption applies (for example retirement on reaching the compulsory age with the required period of service, or retirement due to ill health). Confirm the current conditions with LHDN.'},
  hrdf:{v:NO, r:'Not basic salary or a fixed allowance; excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'notice', ms:'Bayaran gantian notis', label:'Payment in lieu of notice',
  keys:['in lieu of notice','notice pay','indemnity in lieu','resignation in lieu','short notice','pay in lieu','notis'],
  epf:{v:CHK, r:'Generally treated as an indemnity rather than wages, and KWSP lists payment in lieu of notice of termination among payments not liable for contribution — confirm against the current KWSP list before processing.'},
  socso:{v:NO, r:'An indemnity connected with termination is not remuneration for work done and falls outside SOCSO wages.'},
  lhdn:{v:CHK, r:'Usually assessed as compensation for loss of employment rather than ordinary salary, which changes both the PCB treatment and any Schedule 6 exemption. Confirm the treatment with LHDN for the specific case.'},
  hrdf:{v:NO, r:'Not basic salary or a fixed allowance; excluded from levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  clarify:'Which direction is the payment going — the company paying an employee it terminated without notice, or an employee paying the company back for resigning short of notice? Money recovered from a resigning employee is a deduction from net pay, not income, and none of the four contributions arise on it.',
  notes:['The notice period itself is governed by the contract and, for employees within its scope, by the Employment Act 1955 (JTKSM).'],
  extra:['ea']
},
{
  id:'leave-encash', ms:'Bayaran tunai cuti tahunan yang tidak digunakan', label:'Encashment of unutilised annual leave',
  keys:['leave encashment','unutilised leave','annual leave payment','encash leave','replacement leave payment','cuti tahunan bayaran'],
  epf:{v:CHK, r:'Payment in respect of leave is EPF wages when paid during employment; where it forms part of a termination package it follows the termination-benefit treatment. Confirm which applies.'},
  socso:{v:CHK, r:'Payment in respect of leave is SOCSO wages during employment, but payments on termination are excluded. Confirm which applies.'},
  lhdn:{v:YES, r:'Taxable employment income in either case.'},
  hrdf:{v:NO, r:'A one-off encashment is not basic salary or a fixed allowance.'},
  src:['epf','socso','lhdn','hrdf'],
  clarify:'Is the leave being encashed while the employee is still in service, or as part of a final settlement on resignation or termination? The EPF and SOCSO answers differ between the two.'
},
{
  id:'medical', ms:'Faedah atau tuntutan perubatan', label:'Medical, clinic, dental or hospitalisation benefit',
  keys:['medical benefit','medical claim','clinic','hospitalisation','dental','insurance premium','perubatan','medical allowance'],
  epf:{v:NO, r:'A benefit or reimbursement of medical expenses is not remuneration for work and is not EPF wages.'},
  socso:{v:NO, r:'A payment to meet expenses of this kind is not remuneration payable in money to the employee for work done.'},
  lhdn:{v:NO, r:'Medical benefits provided by the employer are exempt from tax; a fixed cash medical allowance, however, is taxable.'},
  hrdf:{v:NO, r:'Not basic salary or a fixed allowance.'},
  src:['epf','socso','lhdn','hrdf'],
  clarify:'Is this a benefit or reimbursement of actual medical cost, or a fixed cash "medical allowance" paid every month regardless of spend? A fixed cash allowance is wages for EPF, SOCSO, PCB and levy.'
},
{
  id:'childcare', ms:'Elaun jagaan anak', label:'Childcare / nursery allowance',
  keys:['childcare','child care allowance','nursery','taska','elaun anak','babysitting allowance'],
  epf:{v:YES, r:'A cash childcare allowance is remuneration and is not in the EPF excluded list.'},
  socso:{v:YES, r:'Included as remuneration payable in money.'},
  lhdn:{v:CHK, r:'Exempt up to the gazetted annual limit for child care allowance for children below the prescribed age; the excess is taxable. Confirm the current limit with LHDN.'},
  hrdf:{v:YES, r:'Subject where paid as a fixed monthly allowance.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'parking', ms:'Elaun atau bayaran tempat letak kereta', label:'Parking allowance or parking fee',
  keys:['parking allowance','parking fee','parking','car park','tempat letak kereta','elaun parkir','parkir'],
  epf:{v:CHK, r:'A fixed cash parking allowance is EPF wages; a parking fee paid by the employer directly to the operator is a benefit, not wages. Confirm which arrangement applies.'},
  socso:{v:CHK, r:'Same distinction — cash to the employee is wages, direct payment to the operator is not.'},
  lhdn:{v:NO, r:'Parking rate or parking allowance is exempt from tax under the gazetted perquisite exemptions.'},
  hrdf:{v:CHK, r:'Subject where paid as a fixed cash allowance; not where the company pays the operator directly.'},
  src:['epf','socso','lhdn','hrdf']
},
{
  id:'director-fee', ms:'Yuran pengarah', label:'Director’s fee',
  keys:['director fee','directors fee','board fee','yuran pengarah'],
  epf:{v:NO, r:'Director’s fee is listed by KWSP among payments not liable for contribution; a working director’s salary under a contract of service is a separate matter and is EPF wages.'},
  socso:{v:NO, r:'A non-executive director is not an employee under a contract of service, so no contribution arises on the fee.'},
  lhdn:{v:YES, r:'Director’s fee is taxable employment income and PCB or the appropriate deduction applies.'},
  hrdf:{v:NO, r:'Not basic salary or a fixed allowance for levy purposes.'},
  src:['epf','socso','lhdn','hrdf'],
  clarify:'Is this person an executive director on the payroll under a contract of service, or a non-executive director receiving only a fee? An executive director’s salary follows the ordinary employee treatment.'
},
{
  id:'employer-contrib', ms:'Caruman syer majikan', label:'Employer’s own EPF / SOCSO / EIS contribution',
  keys:['employer contribution','employer portion','employer share','majikan caruman','company portion'],
  epf:{v:NO, r:'The employer’s contribution is not remuneration paid to the employee, so it is not itself EPF wages.'},
  socso:{v:NO, r:'Employer contributions to a pension or provident fund are expressly excluded from SOCSO wages.'},
  lhdn:{v:NO, r:'The employer’s statutory contribution is not a taxable benefit in the employee’s hands.'},
  hrdf:{v:NO, r:'Employer statutory contributions are excluded from the wages used to compute the levy.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Voluntary employer contributions above the statutory rate can be treated differently for tax — confirm with LHDN if the company contributes above the statutory minimum.']
},
{
  id:'advance', ms:'Pendahuluan gaji atau pinjaman pekerja', label:'Salary advance or staff loan',
  keys:['salary advance','staff loan','advance payment','pendahuluan gaji','loan deduction'],
  epf:{v:NO, r:'An advance is a payment against salary already subject to contribution, not a separate item of wages — do not contribute twice.'},
  socso:{v:NO, r:'Same reasoning: the underlying salary is the contributory item.'},
  lhdn:{v:NO, r:'The salary it advances is what is taxed; the advance itself is not separate income. A loan written off or provided interest-free may be a taxable benefit — confirm with LHDN.'},
  hrdf:{v:NO, r:'Not a separate wage item for levy purposes.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['Deductions from wages to recover an advance are regulated by the Employment Act 1955 — check the JTKSM provisions on permitted deductions and the limit on total deductions.'],
  extra:['ea']
},
{
  id:'maternity', ms:'Bayaran cuti bersalin', label:'Maternity leave pay / maternity allowance',
  keys:['maternity allowance','maternity pay','maternity leave pay','paternity pay','elaun bersalin','bayaran cuti bersalin'],
  epf:{v:YES, r:'Payment in respect of leave is remuneration and forms part of EPF wages.'},
  socso:{v:YES, r:'Payment in respect of leave is included in SOCSO wages.'},
  lhdn:{v:YES, r:'Taxable employment income.'},
  hrdf:{v:YES, r:'Paid as ordinary wages during the leave period, so it forms part of levy wages.'},
  src:['epf','socso','lhdn','hrdf'],
  notes:['The length of maternity and paternity leave and the eligibility conditions are set by the Employment Act 1955 — confirm the current provisions with JTKSM.'],
  extra:['ea']
}
];

/* Special topics answered as prose rather than a four-line grid. */
var TOPICS = [
{
  id:'foreign-worker', ms:'Pekerja asing: KWSP tidak mandatori, PERKESO di bawah Skim Bencana Pekerjaan, EIS tidak terpakai, PCB terpakai.',
  keys:['foreign worker','foreign employee','expatriate','non-citizen','pekerja asing','warga asing','foreigner','work permit holder'],
  title:'Foreign (non-citizen) employees — statutory treatment',
  domains:['EPF','SOCSO','EIS','PCB','HRDF'],
  body:['<ul>'+
    '<li><b>EPF (KWSP):</b> Contribution is not mandatory for non-Malaysian citizens — a foreign employee may elect to contribute, in which case the employer share is a flat statutory amount rather than the normal rate. Confirm the current election procedure and employer rate with KWSP before you set it up in payroll.</li>'+
    '<li><b>SOCSO:</b> Foreign workers are covered under the Employment Injury Scheme (they are not covered by the Invalidity Scheme). Contribution is payable at the Employment Injury rate.</li>'+
    '<li><b>EIS:</b> Does not apply to foreign workers.</li>'+
    '<li><b>Income Tax (PCB):</b> Applies. Where the employee is non-resident for the basis year, deduction is at the non-resident flat rate with no personal reliefs — confirm the current rate and the residence test with LHDN.</li>'+
    '<li><b>HRDF levy:</b> Levy is payable on Malaysian employees; foreign employees are excluded from the levy computation. Confirm against the current HRD Corp levy guidance.</li>'+
    '</ul>',
    'On the wage ceiling point that usually comes with this question: a salary above the SOCSO wage ceiling does <b>not</b> exempt the employee from contribution — the contribution is simply capped at the ceiling. Confirm the current ceiling with PERKESO before running payroll.'],
  src:['epf','socso','lhdn','hrdf'],
  cite:'perkeso.gov.my; kwsp.gov.my'
},
{
  id:'leave-entitlement', ms:'Kelayakan cuti minimum di bawah Akta Kerja 1955.', entitlement:true, cat:'Statutory entitlement',
  keys:['annual leave','sick leave','hospitalisation','hospitalization','paternity','maternity','leave entitlement','cuti tahunan','cuti sakit','cuti bersalin','how many days leave','rest day','public holiday','cuti umum','kids','children','anak','confinement','births','child limit'],
  title:'Statutory leave entitlement — Employment Act 1955 (Amendment 2022)',
  domains:['Employment Act'],
  intro:'These are the <b>statutory minimums</b>. A contract may give more, never less.',
  /* Name a leave type and only that one is answered; ask generally and all five show. */
  items:[
   {id:'annual', k:['annual leave','cuti tahunan','annual'], title:'Annual leave — statutory entitlement',
    html:'<b>Annual leave</b> — <b>8 days</b> for less than 2 years of service, <b>12 days</b> for 2 to 5 years, <b>16 days</b> for more than 5 years.'},
   {id:'sick', k:['sick leave','cuti sakit','sick','medical leave'], title:'Sick leave — statutory entitlement',
    html:'<b>Sick leave</b> (where hospitalisation is not necessary) — <b>14 days</b> if employed less than 2 years, <b>18 days</b> for 2 years or more but less than 5, <b>22 days</b> for 5 years or more (Act 265, s.60F(1)(aa)). Paid sick leave arises only on <b>examination and certification</b> by a registered medical practitioner — one appointed by the employer, or any other practitioner or medical officer where none is appointed or none is obtainable within a reasonable time or distance — or by a dental surgeon under s.60F(1A).'},
   {id:'hosp', k:['hospitalisation','hospitalization','hospital','wad'], title:'Hospitalisation leave — statutory entitlement',
    html:'<b>Hospitalisation leave</b> — <b>60 days</b> in the aggregate in each calendar year where hospitalisation is necessary and so certified (s.60F(1)(bb)). An employee certified ill enough to need hospitalisation but not actually hospitalised for any reason is <b>deemed hospitalised</b> for this purpose.'},
   {id:'maternity', k:['maternity','bersalin','confinement'], title:'Maternity leave — statutory entitlement',
    html:'<b>Maternity leave</b> — <b>98 consecutive days</b>, inclusive of rest days and public holidays. For maternity <i>allowance</i>, the portal states the employee must have worked 90 days in the 9 months before confinement and have fewer than 5 surviving children.'},
   {id:'paternity', k:['paternity','paterniti','father'], title:'Paternity leave — statutory entitlement',
    html:'<b>Paternity leave</b> — <b>7 consecutive days</b> at the ordinary rate of pay per confinement, for a married male employee (s.60FA). Restricted to <b>5 confinements</b>, irrespective of the number of spouses. He must have been employed by the <b>same employer for at least 12 months</b> immediately before the leave starts, and have notified the employer of the pregnancy at least 30 days before the expected confinement, or as early as possible after the birth.'}
  ],
  outro:'<b>Sabah and Sarawak differ.</b> Employees there fall under their own Ordinances, not the Employment Act — ask me about Sabah or Sarawak specifically and I will give you the right reference.',
  src:['act265','mygov','ea'],
  cite:'lom.agc.gov.my; malaysia.gov.my',
  clarify:'Is this employee in Peninsular Malaysia, Sabah or Sarawak? The figures above are the Peninsular position under the Employment Act.',
  uncertain:true,
  caveat:'Figures are from the MyGovernment labour-law portal. Entitlements turn on service length, the employee’s category and the governing statute for the state, and the qualifying conditions above are summarised rather than complete. Confirm against JTKSM (or JTK Sabah / JTK Sarawak) before relying on them in a dispute or a final settlement.'
},
{
  id:'working-hours', ms:'Waktu kerja normal tidak melebihi 45 jam seminggu; Sarawak telah dikurangkan daripada 48 jam.', entitlement:true, cat:'Statutory entitlement',
  keys:['working hours','hours per week','45 hours','48 hours','waktu kerja','jam bekerja','jam kerja','jam seminggu','weekly hours','work week'],
  title:'Statutory working hours',
  domains:['Employment Act'],
  body:[
   '<ul>'+
   '<li><b>Peninsular Malaysia</b> — <b>normal working hours not exceeding 45 hours per week</b> under the Employment Act 1955 (Amendment 2022).</li>'+
   '<li><b>Sabah</b> — the Sabah Labour Ordinance (Amendment) 2024 mirrors the Peninsular position at <b>45 hours per week</b>.</li>'+
   '<li><b>Sarawak</b> — the Sarawak Labour (Amendment) Ordinance 2024 <b>reduced the week from 48 to 45 hours</b>. If your Sarawak payroll still assumes 48, the overtime threshold is wrong.</li>'+
   '</ul>',
   'Read the 45 hours precisely: it is the ceiling on <b>normal</b> working hours, <b>not</b> the total an employee may lawfully work in a week. Overtime sits on top of it and carries its own daily and monthly limits under the Act — confirm those limits with JTKSM before you set an overtime cap in payroll.',
   'Hours worked beyond the statutory week attract overtime. For how overtime is treated statutorily, ask me about overtime — note it is <b>excluded</b> from EPF wages but <b>included</b> in SOCSO/EIS/SKBBK wages.'],
  src:['mygov','ea','sabah','swk'],
  cite:'malaysia.gov.my; jtksm.mohr.gov.my',
  uncertain:true,
  caveat:'Maximum hours, rest days and overtime limits vary by employee category and by the governing statute. Confirm with the labour department for the relevant state before changing an overtime threshold in payroll.'
},
{
  id:'regional-scope', ms:'Semenanjung menggunakan Akta Kerja 1955; Sabah dan Sarawak menggunakan Ordinan Buruh masing-masing.', cat:'Statutory entitlement',
  keys:['sabah','sarawak','east malaysia','labour ordinance','ordinan buruh','peninsular','semenanjung','which act applies','borneo'],
  title:'Which labour statute applies — Peninsular, Sabah or Sarawak',
  domains:['Employment Act'],
  body:[
   'Malaysia does not have one labour statute. Which one governs depends on where the employee works, and getting this wrong is a common source of incorrect leave and overtime calculations for East Malaysian staff.',
   '<ul>'+
   '<li><b>Peninsular Malaysia</b> — <b>Employment Act 1955 (Amendment 2022)</b>, administered by Jabatan Tenaga Kerja Semenanjung Malaysia (JTKSM).</li>'+
   '<li><b>Sabah</b> — <b>Sabah Labour Ordinance (Amendment) 2024</b>, administered by Jabatan Tenaga Kerja Sabah. Its provisions largely mirror the Employment Act, including the 45-hour week and the same leave entitlements.</li>'+
   '<li><b>Sarawak</b> — <b>Sarawak Labour (Amendment) Ordinance 2024</b>, administered by Jabatan Tenaga Kerja Sarawak. Notably it reduced the working week from 48 to 45 hours.</li>'+
   '</ul>',
   'The statutory <b>contribution</b> schemes are national and do not split this way — EPF, SOCSO/EIS/SKBBK, PCB and the HRD Corp levy apply on the same basis across all three regions. It is the labour-law entitlements (hours, leave, termination) that differ.'],
  src:['mygov','ea','sabah','swk'],
  cite:'malaysia.gov.my; jtksabah.gov.my; jtkswk.gov.my'
},
{
  id:'employer-duties', ms:'Tanggungjawab majikan kepada LHDN — borang dan tarikh akhir penghantaran.', cat:'Procedural',
  keys:['cp22','cp22a','cp22b','cp21','cp58','cp8d','cp 8d','borang e','form e','ea form','form ea','form ec','e spc','mytax','e pcb','e cp39','e data','tanggungjawab majikan','employer responsibilit','employer duties','employer obligation','tax clearance','surat penyelesaian','employer number','nombor majikan','submit+pcb','remit+pcb','pcb+deadline','pcb+due','when+pcb','keep+record','record+7 years','borang+lhdn','form+lhdn','berhenti+lhdn','resign+lhdn','cukai+borang'],
  title:'Employer responsibilities to LHDN — forms and deadlines',
  domains:['PCB'],
  intro:'The employer-side obligations under the income tax legislation, as published by LHDN.',
  items:[
   {id:'reg', k:['employer number','nombor majikan','register','daftar','e number','new employer'], title:'Registering as an employer (LHDN)',
    html:'<b>Employer registration</b> — register an employer number (E number) with HASiL.'},
   {id:'pcb', k:['pcb','potongan cukai','mtd','monthly tax deduction','15hb','e pcb','e cp39','e data','remit'], title:'Monthly PCB deduction and remittance',
    html:'<b>Monthly PCB</b> — deduct PCB from the employee’s remuneration using the PCB Schedule or the computerised calculation method, and remit it to HASiL <b>on or before the 15th of the following month</b>. Submission is through the official HASiL applications only — <span class="mono">e-PCB</span>, <span class="mono">e-Data PCB</span> or <span class="mono">e-CP39</span>.'},
   {id:'forme', k:['form e','borang e','cp8d','cp 8d','e filing','annual return'], title:'Form E and CP8D',
    html:'<b>Form E with CP.8D</b> — file <b>on or before 31 March of the following year</b>. Form E is treated as incomplete without CP.8D unless e-Data Praisi was submitted. Companies and Labuan entities must file via e-Filing (e-E).'},
   {id:'ea', k:['ea form','form ea','form ec','statement of remuneration','penyata saraan','february','februari'], title:'Form EA / EC to employees',
    html:'<b>Form EA / EC</b> — give each employee their statement of remuneration <b>on or before the last day of February</b> in the following year.'},
   {id:'cp58', k:['cp58','incentive payment','agent','distributor','pengedar'], title:'Form CP58 — incentive payments',
    html:'<b>Form CP58</b> — prepare and provide to agents, dealers or distributors who received incentive payments, <b>on or before 31 March of the following year</b>.'},
   {id:'records', k:['record','rekod','7 years','tujuh tahun','retention','simpan'], title:'Record keeping',
    html:'<b>Record keeping</b> — keep and maintain records for <b>7 years</b>, accessible to HASiL.'},
   {id:'cp22', k:['cp22','new employee','pekerja baharu','new hire','joins','commence'], title:'CP22 — new employee notification',
    html:'<b>CP22</b> — notify LHDN of a <b>new employee within 30 days</b> after employment starts. Submitted through <span class="mono">e-CP22</span> on the MyTax portal (from 1 September 2024).'},
   {id:'cessation', k:['cp22a','cp22b','cessation','termination','resign','death','kematian','pemberhentian','leaving the company','berhenti'], title:'CP22A / CP22B — cessation or death',
    html:'<b>CP22A</b> (private sector) / <b>CP22B</b> (public sector) — on termination of employment or death: submit <b>not less than 30 days before</b> the cessation, or <b>not more than 30 days after</b> being notified of the death. Filed via <span class="mono">e-SPC</span>; amendments through e-SPC from 1 September 2024, cancellations manually at a HASiL office.'},
   {id:'cp21', k:['cp21','leaving malaysia','leave malaysia','berlepas','departure','overseas','emigrat'], title:'CP21 — employee leaving Malaysia',
    html:'<b>CP21</b> — where an employee is leaving Malaysia for <b>more than 3 months</b>, notify <b>not less than 30 days before</b> the expected date of departure.'},
   {id:'clearance', k:['tax clearance','90 days','withhold','menahan','surat penyelesaian','final pay','final settlement','last pay'], title:'90-day withholding pending tax clearance',
    html:'<b>Withholding of final monies</b> — on cessation, death, or an employee leaving Malaysia for an extended period, withhold any money payable to the employee for <b>90 days</b>, or until the tax clearance letter is received.'}
  ],
  outro:'The 90-day withholding is the one that most often catches payroll out: the final salary cannot simply be paid out with the last payroll run.',
  src:['lhdnEmp','lhdn'],
  cite:'hasil.gov.my',
  uncertain:true,
  caveat:'Deadlines, form versions and submission channels are revised — several of these moved to MyTax / e-SPC in September 2024. Confirm the current channel and due date on the LHDN page above before you file, and note that this page does not state the penalties for late or missed submission.'
},
{
  id:'who-is-covered', ms:'Liputan KWSP dan PERKESO bergantung kepada kontrak perkhidmatan atau perantisan — termasuk pekerja percubaan, sambilan dan sementara.', cat:'Statutory entitlement',
  keys:['probation','percubaan','part time','part-time','sambilan','intern','internship','pelatih','apprentice','perantis','contract staff','temporary staff','pekerja sementara','who must contribute','siapa kena carum','covered+epf','covered+socso','eligible+epf','eligible+socso','trainee','director+gaji','director+salary','director+wages','pengarah+gaji'],
  title:'Who must be covered — EPF and SOCSO',
  domains:['EPF','SOCSO'],
  intro:'Coverage follows the <b>contract</b> — not the job title, the hours worked, or whether the person has finished probation.',
  items:[
   {id:'epf', k:['epf','kwsp'], title:'EPF coverage — who must be contributed for',
    html:'<b>EPF</b> — contributions are payable for <b>any person engaged to work under a contract of service or apprenticeship</b> (s.43(1), EPF Act 1991). Probationers, part-timers, temporary and fixed-term staff are all included; there is no minimum-hours or minimum-wage threshold. The minimum age to register as a member is 14 and the maximum contribution age is 75.'},
   {id:'socso', k:['socso','perkeso','eis','sip'], title:'SOCSO / EIS coverage — who must be registered',
    html:'<b>SOCSO / EIS</b> — all employees engaged under a <b>contract of service or apprenticeship</b> in the private sector must be registered and contributed for. Excluded are permanent federal and state civil servants, the self-employed (other than the self-employed drivers covered by their own scheme), and the sole proprietor or the partners of the business itself. A spouse of the business owner <i>may</i> be registered as an employee (P.U.(A) 144/2018, from 1 July 2018). Contribution applies from age 18 to 60, except for an employee aged 57 or above for whom no contribution was ever payable before age 57.'},
   {id:'director', k:['director','pengarah'], title:'Directors',
    html:'<b>Directors</b> — a director employed under a contract of service is an employee like any other, and the ordinary rules apply to the salary. A non-executive director receiving only fees is not an employee; ask me about <i>director fee</i> for how the fee itself is treated.'},
   {id:'intern', k:['intern','internship','pelatih','apprentice','perantis','practical','trainee'], title:'Interns and apprentices',
    html:'<b>Interns and apprentices</b> — an apprentice under a <b>contract of apprenticeship</b> is expressly within both the EPF and SOCSO definitions. An intern on a purely academic placement with no contract of service or apprenticeship may fall outside. The answer turns on what the arrangement actually is, so confirm the specific case with KWSP and PERKESO rather than assuming either way.'}
  ],
  outro:'Whether a person is covered is a separate question from which of their payments are contributory — ask me about a specific allowance for that.',
  src:['kwspEmp','perkesoCov'],
  cite:'kwsp.gov.my; perkeso.gov.my',
  uncertain:true,
  caveat:'PERKESO states the insured-wage ceiling as RM6,000 a month with effect from 1 October 2024, and both the ceiling and the contribution age rules change by amendment. Confirm the current figures on the agency portals before configuring payroll.'
},
{
  id:'deductions', ms:'Potongan gaji hanya dibenarkan mengikut seksyen 24 Akta Kerja 1955; denda kerana lewat bukan potongan yang sah.', cat:'Statutory entitlement',
  keys:['deduction','potong gaji','potongan gaji','boleh potong','lawful deduction','denda','lambat+gaji','cut+salary','withhold+wages'],
  title:'Deductions from wages — Employment Act s.24',
  domains:['Employment Act'],
  intro:'<b>No deduction may be made from wages except as the Act allows</b> (s.24(1)). The permitted list is closed — anything outside it is unlawful even if the employee agrees to it.',
  items:[
   {id:'automatic', k:['overpayment','advance','terlebih bayar','pendahuluan','without consent'], title:'Deductions allowed without consent (s.24(2))',
    html:'<b>Allowed without consent</b> — (a) recovery of an overpayment of wages made in the <b>three months immediately preceding</b> the month of deduction, where it arose from the employer mistake; (b) indemnity due to the employer under s.13(1); (c) recovery of advances made under s.22, provided no interest is charged; (d) deductions authorised by any other written law — which is what EPF, SOCSO and PCB rely on.'},
   {id:'consent', k:['union','trade union','kesatuan','shares','saham','written request'], title:'Deductions needing the employee written request (s.24(3))',
    html:'<b>Only at the employee written request</b> — payments to a registered trade union or co-operative thrift and loan society, and payments for shares in the employer business offered for sale by the employer.'},
   {id:'dg', k:['director general','ketua pengarah','insurance','provident','third party','accommodation','food'], title:'Deductions needing the Director General permission (s.24(4))',
    html:'<b>Written request plus the Director General prior written permission</b> — payments into a superannuation, provident, welfare or insurance scheme; repayment of interest-bearing advances and the interest on them; payments to a third party on the employee behalf; purchase of the employer goods; and rental for accommodation or the cost of services, food and meals provided by the employer.'},
   {id:'cap', k:['50','fifty','limit','maximum','had','cap'], title:'The 50% ceiling (s.24(8))',
    html:'<b>Total deductions in any one month must not exceed 50% of the wages earned that month</b>. The cap does not apply to an indemnity under s.13(1), to the final wages on termination for amounts still owing, or to a housing-loan repayment permitted in writing by the Director General.'},
   {id:'lateness', k:['lambat','late','denda','penalty','fine','absent','ponteng','tardy'], title:'Deducting for lateness or absence',
    html:'<b>Lateness</b> — a punitive deduction or fine for arriving late is <b>not</b> in the s.24 list, so it is not a lawful deduction from wages. That is a different question from simply not paying for time never worked: absence through imprisonment or attendance in court is dealt with under s.23, and unpaid leave by the incomplete-month formula in s.18A. Where the line falls in a specific case is a question for JTKSM — worth asking before you build it into a payroll rule.'},
   {id:'sickcert', k:['mc','surat doktor','medical certificate','doktor','sick','sakit','certificate'], title:'Sick leave without a medical certificate',
    html:'<b>Sick leave that is not certified</b> — paid sick leave under s.60F arises only after examination and certification by a registered medical practitioner, a medical officer or a dental surgeon. Absence with no such certification is not certified sick leave, so it is not paid sick leave. That makes it a question of unpaid absence, calculated under s.18A — not of deducting a penalty from wages.'}
  ],
  src:['act265','ea'],
  cite:'lom.agc.gov.my; jtksm.mohr.gov.my',
  uncertain:true,
  caveat:'Quoted from the official reprint of Act 265 as at 1 January 2023, which applies to Peninsular Malaysia. Sabah and Sarawak have their own Ordinances. Where money is already in dispute with an employee, treat this as background and take the case to JTKSM.'
},
{
  id:'incomplete-month', ms:'Gaji bulan tidak genap dikira mengikut formula seksyen 18A: gaji bulanan dibahagi bilangan hari tempoh gaji, didarab bilangan hari yang layak.', cat:'Statutory entitlement', entitlement:true,
  keys:['incomplete month','prorate','pro rate','pro-rate','tidak genap','bulan tidak genap','tengah bulan','mid month','partial month','18a','gaji tidak cukup','kira gaji','unpaid leave','cuti tanpa gaji'],
  title:'Wages for an incomplete month — Employment Act s.18A',
  domains:['Employment Act'],
  body:[
   'Where an employee on a <b>monthly rate of pay</b> has not completed a whole month of service, wages for that month are calculated by the statutory formula in s.18A. It applies where the employee:',
   '<ul>'+
   '<li>started work <b>after the first day</b> of the month;</li>'+
   '<li>had employment <b>terminated before the end</b> of the month;</li>'+
   '<li>took <b>leave of absence without pay</b> for one or more days of the month; or</li>'+
   '<li>was absent for national service.</li>'+
   '</ul>',
   'The formula is:',
   '<ul><li><b>Monthly wages &divide; number of days of the particular wage period &times; number of days eligible in the wage period</b></li></ul>',
   'Note the denominator is the <b>number of days of the wage period</b> — not a fixed 26 days, and not the number of working days. A fixed divisor is one of the most common sources of underpayment claims.'],
  src:['act265','ea'],
  cite:'lom.agc.gov.my; jtksm.mohr.gov.my',
  uncertain:true,
  caveat:'Quoted from Act 265 as at 1 January 2023, which applies to Peninsular Malaysia. Section 18A applies notwithstanding s.60I. Sabah and Sarawak follow their own Ordinances.'
},
{
  id:'pregnant-termination', ms:'Menamatkan perkhidmatan pekerja hamil adalah satu kesalahan, kecuali atas pelanggaran kontrak, salah laku, atau penutupan perniagaan.', cat:'Statutory entitlement',
  keys:['pregnant','pregnancy','mengandung','hamil','buang kerja+pregnant','terminate+pregnant','41a'],
  title:'Terminating a pregnant employee — Employment Act s.41A',
  domains:['Employment Act'],
  body:[
   'Where a female employee <b>is pregnant, or is suffering from an illness arising out of her pregnancy</b>, it is an <b>offence</b> for the employer to terminate her services or to give her notice of termination — except on one of three grounds:',
   '<ul>'+
   '<li>wilful breach of a condition of the contract of service under s.13(2);</li>'+
   '<li>misconduct under s.14(1); or</li>'+
   '<li>closure of the employer business.</li>'+
   '</ul>',
   'If such an employee is terminated, <b>the burden of proving that the termination was not on the ground of her pregnancy</b> — or of an illness arising from it — <b>rests on the employer</b>, not on her.',
   'Separately, under s.42, where she remains absent after the eligible period because of a certified illness arising out of her pregnancy and confinement, it is an offence to terminate her until that absence has lasted 90 days after the eligible period expires.'],
  src:['act265','ea'],
  cite:'lom.agc.gov.my; jtksm.mohr.gov.my',
  uncertain:true,
  caveat:'This is a criminal-offence provision with the burden of proof reversed onto the employer. If a termination is contemplated or has already happened, do not act on this summary — take it to your legal adviser or JTKSM.'
},
{
  id:'skbbk', ms:'SKBBK (LINDUNG 24 JAM): mandatori bagi pekerja asing, sukarela bagi pekerja tempatan, dan ditanggung sepenuhnya oleh pekerja.',
  keys:['skbbk','lindung 24','lindung 24 jam','kemalangan bukan bencana kerja','non work accident','bukan bencana kerja','24 jam','akta a1788','lindung faedah'],
  title:'SKBBK — Skim Kemalangan Bukan Bencana Kerja (LINDUNG 24 JAM)',
  domains:['SOCSO','SKBBK'],
  body:[
   'SKBBK, marketed as LINDUNG 24 JAM, is a PERKESO scheme covering accidents that happen <b>outside working hours and are not connected to the employment</b> — at home, on non-work journeys, during personal activities. It sits under Akta 4 alongside the Employment Injury and Invalidity schemes; it is not a replacement for either.',
   '<ul>'+
   '<li><b>Who it applies to:</b> <b>Mandatory for foreign workers.</b> <b>Voluntary for local employees</b> (including permanent and temporary residents) with effect from 8 July 2026, following the Cabinet decision of that date. Contract and part-time staff are eligible; the self-employed are not, and there is no age limit while the person is an employee.</li>'+
   '<li><b>Who pays:</b> Borne <b>entirely by the employee</b>. The employer contributes nothing to this scheme — its role is to deduct from wages and remit monthly.</li>'+
   '<li><b>Rate:</b> phased — <b>0.75%</b> (Phase 1, 1 Jun 2026 to 31 May 2028), <b>1.00%</b> (Phase 2, 1 Jun 2028 to 31 May 2031), <b>1.25%</b> (Phase 3, from 1 Jun 2031), on monthly wages subject to a wage ceiling of <b>RM6,000</b> as at the current FAQ. Rates sit in the Third Schedule of Act A1788.</li>'+
   '<li><b>Combined PERKESO rates once SKBBK applies:</b> employer 1.75% (1.25% Employment Injury + 0.5% Invalidity); employee 1.25% (0.75% SKBBK + 0.5% Invalidity).</li>'+
   '<li><b>Wage base:</b> the same definition as s.2(24) of Akta 4 — all remuneration including leave pay, holiday pay, overtime and work on holidays, <b>excluding</b> statutory contributions, travelling allowance or the value of a travelling concession, payments to defray special expenses of the employment, gratuity on dismissal or retirement, and annual bonus.</li>'+
   '<li><b>Opt-out (local employees):</b> participation is the default — an employee who does nothing is treated as opted in. Opting out runs from 13 July to 31 August 2026 via the Portal Lindung Faedah, or by the Notis Pelepasan Liabiliti form if the system is unavailable. After that date the "Once In, Always In" (Sekali Layak, Terus Layak) principle applies.</li>'+
   '<li><b>More than one employer:</b> only <b>one</b> employer may deduct SKBBK. The employee nominates it on the Borang Penyertaan; PERKESO assigns one if the employee does not choose. Coverage does not stack across employers.</li>'+
   '<li><b>Remittance:</b> monthly to PERKESO via ASSIST 2.0 (FPX), Direct Debit Authorisation, internet banking, or the appointed bank counters. Employers can see who is opted in in the ASSIST Contribution module, marked with <span class="mono">#</span>.</li>'+
   '<li><b>June 2026:</b> that month was mandatory for everyone under the law in force before the 8 July 2026 Cabinet decision, and is <b>not refundable</b>. Refunds are possible from July 2026 onward, claimed <b>by the employer only</b>, through ASSIST (My Sites &rarr; Inspection &rarr; Refund). An employee cannot claim a refund directly.</li>'+
   '<li><b>Non-compliance:</b> PERKESO allows a six-month grace period from enforcement, during which no penalty applies for SKBBK specifically. Beyond that, failure to deduct and remit carries imprisonment of up to two years and/or a fine of up to RM10,000.</li>'+
   '</ul>',
   'One practical trap for payroll: <b>no wages in a month means no SKBBK contribution, and therefore no cover for that month</b>. Unpaid leave months are not covered.'],
  src:['skbbk','socso'],
  cite:'perkeso.gov.my',
  uncertain:true,
  caveat:'Figures above are taken from the PERKESO FAQ version Ver2.1/FAQL24/JUN26 and the scheme page. This scheme changed status in July 2026 and the FAQ has been reissued several times, and the RM6,000 ceiling is stated as applying "at present". Re-check the current FAQ version before you configure a payroll run, and note that whether the employee’s SKBBK contribution attracts any income tax relief is an LHDN question I have not confirmed.'
},
{
  id:'ceiling', ms:'Gaji melebihi siling tidak mengecualikan pekerja — caruman hanya dihadkan pada siling.',
  keys:['above 5000','above rm5,000','above rm5000','exceed ceiling','wage ceiling','salary ceiling','siling gaji','maximum contribution','cap contribution','above 6000','above rm6,000'],
  title:'Wage ceiling — does a high salary remove the obligation?',
  domains:['SOCSO','EIS','EPF'],
  body:['<ul>'+
    '<li><b>SOCSO / EIS:</b> No. A salary above the ceiling does not exempt the employee — the contribution is capped at the ceiling amount and remains payable every month.</li>'+
    '<li><b>EPF:</b> There is no upper wage ceiling for EPF; contribution is on actual wages, with the statutory rate stepping down above a monthly wage threshold and again above the age threshold.</li>'+
    '</ul>',
    'The ceiling amount and the contribution rates are revised from time to time. I will not quote a figure from memory — take the current ceiling and the contribution table from the official source below.'],
  src:['socso','epf'],
  cite:'perkeso.gov.my; kwsp.gov.my'
}
];

/* Rate / ceiling lookups always defer to the official table. */
var RATE_KEYS = [
  {k:['epf rate','kwsp rate','rate+epf','rate+kwsp','kadar+epf','kadar+kwsp','percentage+epf','epf above 60','epf 60 years','60+epf','60+kwsp','contribution rate+epf'],
   d:['EPF'], s:['epf'], what:'the EPF contribution rate (including the reduced rates above the age threshold and above the monthly wage threshold)'},
  {k:['socso rate','perkeso rate','socso ceiling','rate+socso','rate+perkeso','ceiling+socso','siling+socso','kadar+socso','socso table'],
   d:['SOCSO'], s:['socso'], what:'the SOCSO contribution table and the current wage ceiling'},
  {k:['eis rate','sip rate','rate+eis','ceiling+eis','kadar+eis','eis contribution'],
   d:['EIS'], s:['socso'], what:'the EIS (SIP) contribution table and ceiling'},
  {k:['levy rate','hrdf rate','hrd corp levy rate','levy percentage','rate+levy','rate+hrdf','kadar+levy','1%','0.5%'],
   d:['HRDF'], s:['hrdf'], what:'the HRD Corp levy rate applicable to your employee headcount band'},
  {k:['tax relief','pcb rate','tax rate','individual tax rate','relief amount','tax bracket','pcb formula','rate+pcb','kadar+pcb','jadual+pcb'],
   d:['PCB'], s:['lhdn'], what:'the current tax rates, reliefs and the MTD (PCB) computation method'},
  {k:['minimum wage','gaji minimum','minimum salary','gaji minima','upah minimum'],
   d:['Employment Act'], s:['ea'], what:'the current National Minimum Wages Order rate and its effective date'}
];

/* Procedural answers. */
var PROCS = [
  {k:['register+socso','register+perkeso','registration+socso','daftar+socso','borang 2','form 2','assist portal','add+employee+socso'],
   d:['SOCSO'], s:['socso'], title:'Registering a new employee with SOCSO', ms:'Pendaftaran pekerja baharu dengan PERKESO.',
   steps:['Register the employee through the PERKESO ASSIST Portal under your employer account.',
          'A first-time employee is registered with the prescribed employee registration form; the employer itself registers once using the employer registration form.',
          'Contribution starts in the month the employee begins work — late registration attracts interest on late payment.',
          'Submit and pay the monthly contribution through the ASSIST Portal by the statutory due date.']},
  {k:['register+epf','register+kwsp','registration+epf','registration+kwsp','daftar+kwsp','i akaun','add+employee+epf'],
   d:['EPF'], s:['epf'], title:'Registering a new employee with EPF', ms:'Pendaftaran pekerja baharu dengan KWSP.',
   steps:['Register the employee under your employer i-Akaun; an employee without an existing EPF number is registered first.',
          'Contribution is due from the first month of employment, at the rate applicable to the employee’s age and wage band.',
          'Submit the monthly contribution schedule and pay by the statutory due date through i-Akaun.']},
  {k:['register+hrd','registration+hrd','submit+levy','levy+submission','levy+payment','pay+levy','etris','eslip'],
   d:['HRDF'], s:['hrdf'], title:'HRD Corp registration and levy submission', ms:'Pendaftaran dan pembayaran levi HRD Corp.',
   steps:['An employer that meets the registration criteria for its industry and employee headcount must register with HRD Corp.',
          'Levy is computed on the monthly wages of Malaysian employees and paid through the eTRiS system by the statutory due date.',
          'Late payment attracts an interest charge; confirm the current criteria and rate on the HRD Corp portal.']}
];

var OUT_OF_SCOPE = ['visa','immigration','work permit','employment pass','expatriate pass','mm2h','ssm','company registration','incorporat','recruitment strategy','kpi design','performance appraisal','organisation chart','succession plan','marketing','interview question','training content','esg'];
var ESCALATE = ['garnishee','court','industrial court','tribunal','summons','saman','prosecut','audit','tax audit','legal action','lawyer','dispute with','sue','compound','penalty notice','notis penalti','investigation','raid'];

module.exports = {
  SRC, YES, NO, CHK, KB, TOPICS, RATE_KEYS, PROCS, OUT_OF_SCOPE, ESCALATE
};
