/**
 * Extracts the knowledge base out of payroll-compliance-chatbot.html and writes
 * kb-data.js for the bot to require.
 *
 * The HTML file stays the single source of truth: edit the knowledge base there,
 * re-run `npm run sync`, and the bot picks up the change. Nothing is retyped, so
 * the browser demo and the WhatsApp bot can never disagree on a statutory answer.
 */
const fs = require('fs');
const path = require('path');

const HTML = process.env.KB_HTML ||
  [path.join(__dirname, 'payroll-compliance-chatbot.html'),
   path.join(__dirname, '..', 'payroll-compliance-chatbot.html')]
    .find(f => require('fs').existsSync(f));
const OUT = path.join(__dirname, 'kb-data.js');

const src = fs.readFileSync(HTML, 'utf8');

const start = src.indexOf('var SRC = {');
if (start === -1) throw new Error('Could not find "var SRC = {" in ' + HTML);

const escIdx = src.indexOf('var ESCALATE = [', start);
if (escIdx === -1) throw new Error('Could not find "var ESCALATE = [" in ' + HTML);
const end = src.indexOf('];', escIdx);
if (end === -1) throw new Error('Could not find the end of ESCALATE in ' + HTML);

const block = src.slice(start, end + 2);

const header = `/* AUTO-GENERATED by sync-kb.js — do not edit.
 * Source of truth: ${path.basename(HTML)}
 * Re-generate with: npm run sync
 */\n\n`;

const footer = `\n\nmodule.exports = {
  SRC, YES, NO, CHK, KB, TOPICS, RATE_KEYS, PROCS, OUT_OF_SCOPE, ESCALATE
};\n`;

fs.writeFileSync(OUT, header + block + footer, 'utf8');

// Load it back so a syntax error fails here rather than at runtime.
const kb = require(OUT);
console.log('kb-data.js written:');
console.log('  components      :', kb.KB.length);
console.log('  special topics  :', kb.TOPICS.length);
console.log('  rate lookups    :', kb.RATE_KEYS.length);
console.log('  procedures      :', kb.PROCS.length);
console.log('  escalation words:', kb.ESCALATE.length);
